### ISSUE TITLE
Cannot resolve sbt plugin 

### ISSUE THREAD

**Issue by tukushan** [paulp/sbt-extras#103]
The sbt-assembly plugin is not resolved.

To replicate:

```
$ git clone https://github.com/DWiechert/scala-shell.git
$ cd scala-shell
$ rm -rf ~/.ivy2/cache/scala_2.10/sbt_0.13/com.eed3si9n/
$ sbt
```

Error message:
```
...
[info] Resolving com.eed3si9n#sbt-assembly;0.13.0 ...
....
sbt.ResolveException: unresolved dependency: com.eed3si9n#sbt-assembly;0.13.0: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:291)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:188)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:165)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
```

Without the script (ie: ```java -jar ~/.sbt/launchers/0.13.6/sbt-launch.jar```) works fine

**Comment by dwijnand** [comment]
Given you closed #104 with "Apears to be a problem with the project, not sbt-extras" and I hit the same problem as there:

```
/Users/dnw/Desktop/scala-shell/build.sbt:7: error: not found: value EclipseKeys
EclipseKeys.withSource := true
^
```

I think this ticket is invalid.
